// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview CV parsing AI agent.
 *
 * - parseCV - A function that handles the CV parsing process.
 * - ParseCVInput - The input type for the parseCV function.
 * - ParseCVOutput - The return type for the parseCV function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ParseCVInputSchema = z.object({
  cvData: z.string().describe('The CV data to parse.'),
});
export type ParseCVInput = z.infer<typeof ParseCVInputSchema>;

const ParseCVOutputSchema = z.object({
  skills: z.array(z.string()).describe('The skills listed in the CV.'),
  experience: z.array(z.string()).describe('The experience listed in the CV.'),
  education: z.string().describe('The education listed in the CV.'),
  militaryService: z.string().describe('The military service information from the CV.'),
  personalSkills: z.array(z.string()).describe('The personal skills listed in the CV.'),
});
export type ParseCVOutput = z.infer<typeof ParseCVOutputSchema>;

export async function parseCV(input: ParseCVInput): Promise<ParseCVOutput> {
  return parseCVFlow(input);
}

const prompt = ai.definePrompt({
  name: 'parseCVPrompt',
  input: {schema: ParseCVInputSchema},
  output: {schema: ParseCVOutputSchema},
  prompt: `You are an expert CV parser. You will extract the skills, experience, education, military service information, and personal skills from the CV data provided.

CV Data: {{{cvData}}}

 skills:
{{#each skills}}- {{{this}}}
{{/each}}

  experience:
{{#each experience}}- {{{this}}}
{{/each}}

  education:{{{education}}}

 militaryService:{{{militaryService}}}

personalSkills:
{{#each personalSkills}}- {{{this}}}
{{/each}}`,
});

const parseCVFlow = ai.defineFlow(
  {
    name: 'parseCVFlow',
    inputSchema: ParseCVInputSchema,
    outputSchema: ParseCVOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
